### ISSUE TITLE
Global shortcuts for Volume Up/Down doesn't work

### ISSUE THREAD

**Issue by madjoe** [Zren/plasma-applet-volumewin7mixer#10]
Unfortunately, the global shortcuts for Volume Up/Down doesn't work anymore, right after a vanilla installation of this app. I should still be able to use those shortcut buttons for a quick and easy volume adjustment. :(

**Comment by Zren** [comment]
You need to restart plasmashell (relog).

The global shortcut were bound to the default "audio volume" widget when it loads. My widget does the same, but both only try to "grab" the global shortcut when the widget is loaded. So if you first add the win7 widget (and it fails to capture the global shortcuts), then remove the default widget, you no longer have the global shortcut until you relog.

**Comment by madjoe** [comment]
Well, I installed win7 widget by installing it through pamac only and restarted my Manjaro right after. Therefore, I restarted plasmashell already. After the system rebooted, the global shortcuts were not available. You suggest me to remove the default widget? I disabled it through "Configure system tray" > and removing the checkmark from the default "Audio volume". Still no improvement.

**Comment by Zren** [comment]
Does running the command:

```bash
qdbus org.kde.kglobalaccel /component/kmix invokeShortcut "increase_volume"
```

raise the volume?

**Comment by madjoe** [comment]
> ```shell
> qdbus org.kde.kglobalaccel /component/kmix invokeShortcut "increase_volume"
> ```

Hm... after second restart it all works as expected. Strange. Yes, I am using a stable branch of Manjaro KDE.
