### ISSUE TITLE
Changing the volume with the mousewheel while hovering over panel

### ISSUE THREAD

**Issue by roachsinai** [Zren/plasma-applet-volumewin7mixer#11]
Thanks for your work!

I know I could change volume hovering over applet right now, but I want it more as I use autohotkey on Win10 which let me change volume with mousewheel while hovering over taskbar.

So, could you add this option?

**Comment by roachsinai** [comment]
btw, the name should be win10, lol.

**Comment by Zren** [comment]
Win10 uses a horizontal slider.

Install win7showdesktop and put it in your bottom right corner of the panel, then lock the widgets. You can easily control volume by flinging to the bottom right corner.

**Comment by roachsinai** [comment]
Thanks for your reply. But for me, it well be better if mousewheel could change volume while mouse over panel(anywhere, left, right, center).

**Comment by Zren** [comment]
To do that, you'd need to either edit every single widget in your panel, or edit the "panel widget", or something. I'm not going to try hijacking the mousewheel of the entire panel.

There's this which defines the 

* https://github.com/KDE/plasma-desktop/blob/master/desktoppackage/contents/defaults#L11
* `/usr/share/plasma/shells/org.kde.plasma.desktop/contents/defaults`
* https://github.com/KDE/plasma-workspace/tree/master/containmentactions

But I've never tried to write a custom containmentaction.

It's probably possible to do this feature in my widget, but would break the mousewheel of every other widget in the panel, and possibly break the middle mouse click, and maybe even left/right click + drag. You wouldn't be able to do it with this widget in the systemtray either... without it being even more complicated.

Basically... no.

**Comment by roachsinai** [comment]
Thanks a lot!
