### ISSUE TITLE
support for alsa

### ISSUE THREAD

**Issue by alekksander** [Zren/plasma-applet-volumewin7mixer#6]
please add support for alsa. this applet has everything needed but support for alsa. please consider adding it.

thank You

**Comment by Zren** [comment]
My widget  just styles the default widget `plasma-pa` (pa = PulseAudio) differently. Win7Mixer uses `plasma-pa`'s QML library but, which is specifically written for PulseAudio.  If you want to use alsa, install `kmix` which should still work.
